export const skillList = [
    {
        skill:'FrontEnd',
        img: [
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'BackEnd',
        img:[
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'BackEnd',
        img:[
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'Mobile App',
        img:[
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'Deployment',
        img:[
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'Community',
        img:[
            {img:"/src/assets/img/html-logo.png"},
            {img:"/src/assets/img/css-logo.png"},
            {img:"/src/assets/img/js-logo.png"}
        ]
    },
    {
        skill:'Extra',
        img:[
            {img:"/src/assets/img/html-logo.png"},
        ]
    },

]