export const infoList = [
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"이름",
        detail:"서가희"
    },
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"생년월일",
        detail:"00.10.26"
    },
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"주소지",
        detail:"경기도 고양시 일산서구"
    },
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"연락처",
        detail:"010-5833-3159"
    },
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"이메일",
        detail:"skh9797@naver.com"
    },
    {
        img:"/src/assets/img/telephone-icon.png",
        info:"학력",
        detail:"인천대학교(임베디드시스템공학과)"
    },
]